# Site wide configuration

title:            Jonathan Barket dot com
locale:           en_US
url:              /jonathanbarket.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Jonathan Barket
  avatar: bio-photo.jpg
  bio: "Front End Enthusiast. Developer Advocate. Instructor at The Iron Yard."
  email:
  disqus-shortname:
  twitter: jbarket
  facebook: #username
  google:
    plus: #username
    analytics: UA-73083729-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jbarket
  stackoverflow: 1323052/jbarket
  linkedin: jbarket
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
